### ISSUE TITLE
App dies if passed path isn't found for any reason

### ISSUE THREAD

**Issue by Mgamerz** [Exkywor/FSvBSCustomCloneUtility#1]
**Describe the bug**
Passing any invalid command line path will crash the app

**To Reproduce**
Start application with any command line args that don't represent a valid path. (For mod manager boot passthrough to work you have to use --me1path/--me2path/--me3path/--le1path/--le2path/--le3path)

**Expected behavior**
Just ignore bad paths.

**Log**
Go to the FSvBSC3 folder, find the log file corresponding to the hour when the error occurred. Copy the messages inside the log into an online pastebin, then copy the link to that here.

Log folder doesn't exist.

**Stack Trace**
If you see an error dialog with details or a copy button, post those details here. 
```
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mgame\Source\Repos\ME3Tweaks\MassEffectModManager\MassEffectModManagerCore\bin\x64\Debug\net5.0-windows8.0\win10-x64\resources\FAQ.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at FSvBSCustomCloneUtility.ViewModels.MainWindowViewModel.LoadFAQ()
```

**Additional context**

**Comment by Exkywor** [comment]
I'm gonna work on that this week. Right now it just takes the first argument and assumes it's the path, and should ignore it if it's a bad path.
There should be a log file in the same file as the .exe.
Hmm, that stack track refers to the faqs file not being found either. It should be copied by VS to the folder so it can be found, I wonder what's happening there.
